name: resq
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  material_color_utilities: ^0.11.1
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.0+3
  font_awesome_flutter: ^10.8.0
  google_nav_bar: ^5.0.7
  shared_preferences: ^2.5.1
  random_avatar: ^0.0.8
  dice_bear: ^0.1.7
  flutter_svg: ^2.0.17
  intl_phone_field: ^3.2.0
  geolocator: ^13.0.2
  audioplayers: ^6.1.1
  file_picker: ^8.3.1
  image_picker: ^1.1.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/imgs/
    - assets/imgs/logos/

  fonts:
    - family: TT Norms Pro
      fonts:
        - asset: assets/fonts/TT Norms Pro Light.otf
        - asset: assets/fonts/TT Norms Pro Regular.otf
        - asset: assets/fonts/TT Norms Pro Medium.otf
        - asset: assets/fonts/TT Norms Pro Bold.otf
          weight: 700  # Instead of "style: regular"
