name: resq
description: "A new Flutter project."
publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  material_color_utilities: ^0.11.1
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.0+3
  font_awesome_flutter: ^10.8.0
  google_nav_bar: ^5.0.7
  shared_preferences: ^2.5.1
  random_avatar: ^0.0.8
  dice_bear: ^0.1.7
  flutter_svg: ^2.0.17
  intl_phone_field: ^3.2.0
  geolocator: ^14.0.0
  file_picker: ^10.1.2
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  firebase_core: ^3.12.1
  go_router: ^15.0.0
  flutter_bloc: ^9.1.0
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  equatable: ^2.0.7
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  country_code_picker: ^3.2.0
  firebase_storage: ^12.4.4
  rxdart: ^0.28.0
  intl: ^0.20.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  connectivity_plus: ^6.1.3
  maps_launcher: ^3.0.0+1
  record: ^6.0.0
  just_audio: ^0.10.0
  cached_network_image: ^3.4.1
  geocoding: ^3.0.0
  flutter_local_notifications: ^19.0.0
  firebase_app_check: ^0.3.2+5
  heif_converter: ^1.0.1

  uuid: any
  path: any
  path_provider: any
  crypto: any
  bloc: any
  provider: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/imgs/
    - assets/imgs/logos/

  fonts:
    - family: TT Norms Pro
      fonts:
        - asset: assets/fonts/TT Norms Pro Light.otf
        - asset: assets/fonts/TT Norms Pro Regular.otf
        - asset: assets/fonts/TT Norms Pro Medium.otf
        - asset: assets/fonts/TT Norms Pro Bold.otf
          weight: 700  # Instead of "style: regular"
